---
# tasks file for users

- name: add new user
  ansible.builtin.user:
    name: controller
    state: present
    shell: /bin/bash
    createhome: yes
    home: /home/controller

- name: add ssh-key to user
  ansible.posix.authorized_key:
    user: controller
    key: "{{ lookup('file', '/home/ansible/.ssh/id_rsa.pub') }}"
